using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

// generated by chatgpt
public class UITutorialDimmer : Image
{
    private const int MAX_HOLES = 8;

    private static readonly int HoleCountId = Shader.PropertyToID("_HoleCount");
    private static readonly int HoleRectsId = Shader.PropertyToID("_HoleRects");
    
    private readonly List<RectTransform> _targets = new();
    private readonly Vector4[] _holeRects = new Vector4[MAX_HOLES];
    
    public void SetTargets(List<RectTransform> argTargets)
    {
        _targets.Clear();

        if (argTargets != null)
        {
            _targets.AddRange(argTargets);
        }

        UpdateShaderData();
    }

    private void UpdateShaderData()
    {
        int count = Mathf.Min(_targets.Count, MAX_HOLES);

        for (int i = 0; i < MAX_HOLES; i++)
        {
            _holeRects[i] = Vector4.zero;
        }

        for (int i = 0; i < count; i++)
        {
            RectTransform target = _targets[i];

            if (target == null)
                continue;

            Vector3[] corners = new Vector3[4];
            target.GetWorldCorners(corners);

            Vector2 min = RectTransformUtility.WorldToScreenPoint(
                null,
                corners[0]);

            Vector2 max = RectTransformUtility.WorldToScreenPoint(
                null,
                corners[2]);

            _holeRects[i] = new Vector4(
                min.x / Screen.width,
                min.y / Screen.height,
                max.x / Screen.width,
                max.y / Screen.height);
        }

        material.SetInt(HoleCountId, count);
        material.SetVectorArray(HoleRectsId, _holeRects);
    }

    public override bool Raycast(
        Vector2 argScreenPoint,
        Camera argEventCamera)
    {
        foreach (RectTransform target in _targets)
        {
            if (target == null)
                continue;

            if (RectTransformUtility.RectangleContainsScreenPoint(
                target,
                argScreenPoint,
                null))
            {
                return false;
            }
        }

        return true;
    }
}