using UnityEngine;

public enum StringID
{
    None = 0,
    GameStart,
    
    Yes = 101,
    No,
    ConfirmRestartStage = 201,
    ConfirmExitStage,
    ConfirmExitGame,
    
    // Option
    Option = 251,
    Sound,
    Sensitivity,
    Frame,
    Quality,
    Language,
    Frame30,
    Frame60,
    FrameMax,
    QualityLow,
    QualityMedium,
    QualityHigh,
    LangEnglish,
    LangKorean,
    
    // HqPanel
    HqInfo = 301,
    Hp,
    Shield,
    Entity,
    MenuSelect,
    LaneSelect,
    SlotSelect,
    EntitySelect,
    EntityStat,
    Top,
    Mid,
    Bottom,
    Slot,
    Lv,
    Producing,
    Produce,
    EntityUpgrade,
    HqUpgrade,
    ConfirmEntitySelect,
    StopProducing,
    ConfirmStopProducing,
    NowProducingEntity,
    Level,
    NotEnoughGold,
    Upgrade,
    MaxHp,
    Gps,
    MaxTier,
    MaxSlot,
    ProductionBonus,
    ConfirmHqUpgrade,
    MaxLevel,
    ConfirmAddSlot,
    AddSlot,
    Gold,
    MaxGrade,
    SlotUpgrade,
    SlotDowngradeNotice,
    
    // Result
    Victory = 501,
    Defeat,
    Clear,
    Success,
    Fail,
    Best,
    NewRecord,
    ClearTimeMission,
    HqHpMission,
    Retry,
    Exit,
    Ok,
    Selected,
    
    // StageInfo
    Start,
    ClearReward,
    CommanderSkill,
    SkillSelect,
    Active,
    Passive,
    
    // worldSelectInfo
    World,
    Select,
    WorldSelect,
    
    // Entity - Pioneer Name
    Police = 10001,
    Phalanx,
    Security,
    Piercer,
    SpecialForce,
    Breacher,
    AssaultRifle,
    HeavyGunner,
    HydroPuncher,
    ShadowReaper,
    TheThunder,
    AegisStorm,
    ElectroBlade,
    PlasmaSlasher,
    VoidBullet,
    SonicDisruptor,
    
    // Entity - Revolt Name
    SteelBaton = 20001,
    WireStriker,
    MasterGang,
    MadGas,
    UnknownSamurai,
    SteelWall,
    SharpShooter,
    DevilDrone,
    ChainsawBot,
    PyroManiac,
    CentauriCanon,
    MultiLauncher,
    ChimeraBeast,
    Overload,
    BloodyCanon,
    DestroyLaser,
    
    // Skill Name
    LaserStrike,
    Bomb,
    EMPField,
    DefensiveMatrix,
    HQDefenceSystem,
    CombatDrive,
    Frenzy,
    VitalReboot,
    Glitch,
    Crunch,
    GoldRush,
    OverMining,
    
    LaserStrike_desc,
    Bomb_desc,
    EMPField_desc,
    DefensiveMatrix_desc,
    HQDefenceSystem_desc,
    CombatDrive_desc,
    Frenzy_desc,
    VitalReboot_desc,
    Glitch_desc,
    Crunch_desc,
    GoldRush_desc,
    OverMining_desc,
}
