using UnityEngine;

public enum StringID
{
    None = 0,
    
    Yes = 101,
    No,
    ConfirmRestartStage = 201,
    ConfirmExitStage,
    
    Option = 251,
    Sound,
    Sensitivity,
    Frame,
    Quality,
    Language,
    Frame30,
    Frame60,
    FrameMax,
    QualityLow,
    QualityMedium,
    QualityHigh,
    LangEnglish,
    LangKorean,
    
    HqInfo = 301,
    Hp,
    Shield,
    Entity,
    MenuSelect,
    LaneSelect,
    SlotSelect,
    EntitySelect,
    EntityStat,
    Top,
    Mid,
    Bottom,
    Slot,
    Lv,
    Producing,
    Produce,
    EntityUpgrade,
    HqUpgrade,
    ConfirmEntitySelect,
    StopProducing,
    ConfirmStopProducing,
    NowProducingEntity,
    Level,
    NotEnoughGold,
    Upgrade,
    MaxHp,
    Gps,
    MaxTier,
    MaxSlot,
    ProductionBonus,
    ConfirmHqUpgrade,
    MaxLevel,
    ConfirmAddSlot,
    AddSlot,
    Gold,
    MaxGrade,
    SlotUpgrade,
    SlotDowngradeNotice,
    
    Victory = 501,
    Defeat,
    Clear,
    Success,
    Fail,
    Best,
    NewRecord,
    ClearTimeMission,
    HqHpMission,
    Retry,
    Exit,
    Ok,
    Selected,
    
    // Entity - Pioneer Name
    Police = 10001,
    Phalanx,
    Security,
    Agent,
    SpecialForce,
    Breacher,
    AssaultRifle,
    Commander,
    HydroPuncher,
    ShadowReaper,
    TheThunder,
    AegisStorm,
    ElectroBlade,
    PlasmaSlasher,
    BloodyCanon,
    SonicDisruptor,
    
    // Entity - Revolt Name
    SteelBaton = 20001,
    WireStriker,
    MasterGang,
    MadGas,
    UnknownSamurai,
    SteelWall,
    SharpShooter,
    DroneBomber,
    ChainsawBot,
    PyroManiac,
    CentauriCanon,
    MultiLauncher,
    Whiplash,
    Overload,
    VoidBullet,
    DestroyLaser,
}
